"""
Simple signal + outcome logger for CapriQuant.

Logs every signal generated by the structure engine to a local JSONL file.
This is the minimum required data for serious performance analysis and
future machine learning on your edge.

Usage:
    from app.utils.signal_logger import log_signal
    log_signal(signal_dict, outcome_r_multiple=None)
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True)
SIGNAL_LOG = LOG_DIR / "signals.jsonl"


def log_signal(signal: Dict, outcome: Optional[Dict] = None) -> None:
    """
    Append a signal + optional outcome to the log.
    """
    record = {
        "timestamp": datetime.utcnow().isoformat(),
        "signal": signal,
        "outcome": outcome,
    }
    with open(SIGNAL_LOG, "a") as f:
        f.write(json.dumps(record, default=str) + "\n")


def load_signals() -> list:
    """Load all logged signals for analysis."""
    if not SIGNAL_LOG.exists():
        return []
    with open(SIGNAL_LOG) as f:
        return [json.loads(line) for line in f]
